experiment:
  name: "unet_resnet_exp"
  seed: 42
  deterministic: true

paths:
  raw: "data/raw"
  processed: "data/processed"
  outputs: "outputs"

data:
  train_split: "data/processed/splits/train.txt"
  val_split: "data/processed/splits/val.txt"
  img_dir: "data/raw/train_images"
  mask_dir: "data/processed/masks_png"
  img_size: [256, 800] # GPU dostu, CPU daha az yorulur

training:
  device: "cuda"
  batch_size: 16 # GPU VRAM daha iyi kullanılır
  num_workers: 2 # CPU yükü azalır, GPU beslenir
  epochs: 5
  lr: 0.001
  clip_grad_norm: 1.0
  use_amp: true
  early_stopping: 5
  save_every: 1
  start_epoch: 1
  monitor: "dice_mean"
  checkpoint_dir: outputs/checkpoints

model:
  in_channels: 3
  out_channels: 4
  encoder_name: "resnet18"
  encoder_weights: "imagenet"
  norm: "batch"
  dropout: 0.0
  num_groups: 8
  up_mode: "transpose"

loss:
  type: "BCEDiceLoss"
  params:
    bce_weight: 0.7
    dice_weight: 0.3
    smooth: 1.0
    pos_weight: [1.0, 5.0, 10.0, 2.0]

metrics:
  dice:
    threshold: 0.5
    smooth: 1e-6
  iou:
    threshold: 0.5
    smooth: 1e-6

logging:
  save_dir: "outputs/checkpoints"
  plots_dir: "outputs"
  loggers: ["tensorboard"]
  wandb_project: "steel_defect_unet"

preprocess:
  save_masks: ["png"]
  make_splits: true
  num_visualize: 20
  n_folds: 5
  mini_ratio: 0.1
  train_file: "data/processed/splits/train.txt"
  val_file: "data/processed/splits/val.txt"
  train_file_mini: "data/processed/splits/train_mini.txt"
  val_file_mini: "data/processed/splits/val_mini.txt"
