experiment_name: "steel_defect_unet_resnet18"

data:
  train_csv: "data/raw/train.csv"
  train_images_dir: "data/raw/train_images"
  val_split: 0.2
  image_height: 256
  image_width: 1600 #1600
  num_classes: 4

training:
  batch_size: 2
  num_workers: 2
  epochs: 2
  learning_rate: 1e-4
  weight_decay: 1e-5
  device: "cuda"

scheduler:
  mode: "max"            # valid dice için max
  factor: 0.5            # LR azaltma oranı
  patience: 2            # kaç epoch beklesin
  verbose: true

early_stopping:
  patience: 5            # valid dice iyileşmezse dur
  mode: "max"

model:
  backbone: "resnet18"
  pretrained: true
  decoder_mode: "concat"    # add | concat


logging:
  output_dir: "outputs/"
  checkpoint_dir: "checkpoints/"
  save_every: 5
