experiment:
  name: "unet_baseline"
  seed: 42

data:
  train_split: "data/processed/splits/train_mini.txt"
  val_split: "data/processed/splits/val_mini.txt"
  img_dir: "data/raw/train_images"
  mask_dir: "data/processed/masks_png"

training:
  device: "cpu" # cpu da yazabilirsin
  batch_size: 2
  num_workers: 0
  epochs: 10 # 🔥 artık "epochs"
  lr: 0.0001
  checkpoint_dir: "outputs/checkpoints"

model:
  in_channels: 3
  out_channels: 4
  backbone: "unet_effnet" # ileride fpn/effnet gibi varyantlara geçilebilir

loss:
  type: "BCEDiceLoss"
  bce_weight: 0.75
  dice_weight: 0.25

logging:
  save_dir: "outputs/checkpoints"
  plots_dir: "outputs"
